/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package signauth;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */

public class MainFrame extends javax.swing.JFrame {
    
    private final Canvas canvas;
    private String enrolledUser;
    private ImageHandler imhandler;
    private MDF mdf;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        canvas = new Canvas(); 
        this.getContentPane().add(canvas);
        canvas.setBounds(70, 60, 160, this.getHeight() - 150);
        clearBtn.addActionListener(canvas);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearBtn = new javax.swing.JButton();
        enrollBtn = new javax.swing.JButton();
        authBtn = new javax.swing.JButton();
        authBtn1 = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        resultLbl = new javax.swing.JLabel();
        resultVal = new javax.swing.JLabel();
        signhere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signature Authentication");
        setResizable(false);

        clearBtn.setText("Reset Kanvas");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        enrollBtn.setText("Daftarkan!");
        enrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBtnActionPerformed(evt);
            }
        });

        authBtn.setText("Identifikasi!");
        authBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authBtnActionPerformed(evt);
            }
        });

        authBtn1.setText("Keluar");
        authBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authBtn1ActionPerformed(evt);
            }
        });

        lbl1.setText("Ketik Nama Anda untuk mendaftar");

        resultLbl.setText("Result :");

        signhere.setText("TANDA TANGAN DISINI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(signhere)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enrollBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTF)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(resultLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl1))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signhere, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clearBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enrollBtn)
                .addGap(33, 33, 33)
                .addComponent(authBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLbl)
                    .addComponent(resultVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(authBtn1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollBtnActionPerformed
        enrolledUser = nameTF.getText();
        mdf = new MDF();
        
        if(enrolledUser.equals(""))
        {
            showMessage("Pemberitahuan", "Kolom nama wajib diisi.", "warning");
        }
        else
        {
            imhandler = new ImageHandler(this.canvas);
            try {
                mdf.extractFeature(imhandler);
                mdf.saveFeatures(enrolledUser);
            } catch (FileNotFoundException ex) {}
            showMessage("Enrollment Berhasil", "Data berhasil disimpan.", "info");
        }
    }//GEN-LAST:event_enrollBtnActionPerformed
    
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void authBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_authBtn1ActionPerformed

    private void authBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authBtnActionPerformed
        mdf = new MDF();
        imhandler = new ImageHandler(this.canvas);
        mdf.extractFeature(imhandler);
        
        double[][] features = mdf.getFeatures();
        double minDist = 1000.0;
        
        BufferedReader br = null;
        
        File dirFeature = new File("E:/Signature Dataset/MDF features");
        File[] files = dirFeature.listFiles();
        int n = files.length;
        String result = "";
        
        for(int i=0; i<n; i++)
        {
        try
        {
            StringBuilder content = new StringBuilder();
            try
            {
                String strPerLine = null;
                br = new BufferedReader(new FileReader(files[i].getCanonicalPath()));

                while((strPerLine = br.readLine()) != null)
                {
                    content.append(strPerLine);
                }
            }
            finally
            {
                if(br != null) br.close();
            }
            
            String[] tfdf = content.toString().split(";");
            
            double sum = 0.0;
            double tfTrain;
            double dfTrain;
            double trainFeatures;
            double tfTest;
            double dfTest;
            double testFeatures;
                    
            for(int kk=0; kk<1180; kk++)
            {
                String[] temp = tfdf[n].split("-");
                tfTrain = Double.parseDouble(temp[0]);
                dfTrain = Double.parseDouble(temp[1]);
                trainFeatures = tfTrain + dfTrain;
                
                tfTest = features[0][n];
                dfTest = features[1][n];
                testFeatures = tfTest + dfTest;
                
                sum += (double) (Math.pow((trainFeatures - testFeatures), 2.0));
            }
            
            if(Math.sqrt(sum) <= minDist)
            {
                minDist = Math.sqrt(sum);
                result = files[i].getName();
                result = result.substring(0, result.length()-4);
            }
        }
        catch(IOException ioe)
        {}
        } 
        resultVal.setText(""+result);
    }//GEN-LAST:event_authBtnActionPerformed
    
    private void showMessage(String title, String msg, String type)
    {
        int a = 0;
        switch(type)
        {
            case "error":
                a = JOptionPane.ERROR_MESSAGE;
            break;
            case "warning":
                a = JOptionPane.WARNING_MESSAGE;
            break;
            default:
                a = JOptionPane.INFORMATION_MESSAGE;
            break;
        }
        JOptionPane.showMessageDialog(this, msg, title, a);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authBtn;
    private javax.swing.JButton authBtn1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton enrollBtn;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JLabel resultVal;
    private javax.swing.JLabel signhere;
    // End of variables declaration//GEN-END:variables
}
